version: '3.7'
services:
  db:
    container_name: dramatize-db
    image: dramatize/db
    build: ../../../db
    restart: always
    environment:
      # TODO: move to .env
      POSTGRES_PASSWORD: dramatize
      POSTGRES_DB: dramatize
    ports:
      - 5432:5432
    volumes:
       - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 10s
      retries: 15

  api:
    container_name: dramatize-api
    image: dramatize/api
    build: ../../../api
    depends_on:
      db:
        condition: service_healthy


  client:
    container_name: dramatize-client
    image: dramatize/client
    build: ../../../client
    depends_on:
      - api
